apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: mongo-secret
data:
  mongo-user: azhzZGVtb3VzZXI= #echo -n k8sdemouser | base64
  mongo-password: azhzZGVtb3VzZXI= #echo -n k8sdemopassword | base64
